# Use uma imagem Python leve
FROM python:3.10-slim

# Define o diretório de trabalho
WORKDIR /app

# Copia apenas o requirements para aproveitar cache
COPY requirements.txt .

# Instala as dependências
RUN pip install --no-cache-dir -r requirements.txt

# Copia todo o seu código para dentro do container
COPY . .

# Exponha a porta padrão que o Streamlit usará
EXPOSE 8501

# Comando para rodar o Streamlit
CMD ["streamlit","run","app.py","--server.port","8501","--server.address","0.0.0.0"]
